### ISSUE TITLE
Add Chibi-Scheme

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#1]
I wrote a `Dockerfile` for Chibi-Scheme here: https://github.com/lassik/scheme-docker/tree/chibi. Do you want to include it? I can't send you a PR because we use orphan branches.

**Comment by weinholt** [comment]
Thanks! I have pushed it and created builds on Docker hub.

I would like to have a script wrapper before we close this issue. Either as described in r6rs-app and/or SRFI-22.

**Comment by lassik** [comment]
Which one do you think would be more appropriate, considering Chibi is R7RS-only? I'm not familiar with the details.

**Comment by weinholt** [comment]
Gauche suggests to use SRFI 22 and install gosh as scheme-r7rs, meaning it will work with `#!/usr/bin/env scheme-r7rs`. (I'll update the Gauche build to have this alias).

Here's the documentation:
https://practical-scheme.net/gauche/man/gauche-refe/Writing-Scheme-scripts.html

I guess we can symlink chibi-scheme to scheme-r7rs to get the same functionality with Chibi.

**Comment by lassik** [comment]
It seems reasonable to follow Gauche's approach. But `chibi-scheme -h` says: `-r[<main>] - run a SRFI-22 main`. So we should make a small wrapper that gives the `-r` flag.
