### ISSUE TITLE
IronScheme command and banner 

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#13]
We should update IronScheme's Dockerfile once the next version of IS is out.

Pertinent discussion from #3:

@weinholt :
> when IronScheme starts a script, should it actually be printing the logo/banner first? It seems unusual. I'm thinking it's better to reserve the banner for interactive use.

@leppie:
> I think it just does. If you create a symlink to the exe called `isc` it should not print one. Not sure if this works on Linux though. I will remove the logo if a file has been passed in. Thanks

See also https://github.com/leppie/IronScheme/issues/37 about whether IronScheme's official command name is `isc` or `ironscheme`

**Comment by lassik** [comment]
TODO:

* Add `/usr/local/bin/scheme-banner` command and set it as `CMD` in Dockerfile.
* Change `/usr/local/bin/scheme-script` to no longer pass the `/nologo` flag.

**Comment by lassik** [comment]
`ironscheme`, `scheme-banner` and `scheme-script` can probably all be the same command.

**Comment by leppie** [comment]
@weinholt fixed in latest release

**Comment by weinholt** [comment]
@leppie Thank you much!

**Comment by lassik** [comment]
Thanks a lot for the quick turnaround @leppie!
