### ISSUE TITLE
Slim images

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#14]
The current Docker images are quite big (e.g. 123M for Chibi, 236M for Vicare). Are there easy ways to reduce them? I noticed that Debian has official `-slim` images. According to a blog post, those are about half the size of the normal Debian images.

Is it possible to build using a normal Debian image but run the corresponding `-slim` image?

**Comment by weinholt** [comment]
Yes, this should be possible. It could happen that some dependency is missing, but you'll notice that when the image doesn't start properly.

**Comment by lassik** [comment]
Well, chibi shrunk to 92M using `buster-slim` so the reduction was only 30M. `buster-slim` by itself is 70M. For some reason, it even comes with Perl 5!

**Comment by lassik** [comment]
Some [unofficial `minideb` images](https://dzone.com/articles/minideb-a-minimalist-debian-based-docker-image) are 50M, so 20M smaller than `-slim`.

For really small sizes, Alpine is the most often used distro. But it's based on musl libc which may cause problems for some Schemes. Also I guess you want to stick with Debian since you contribute to it. I may try to spin up some Alpine-based images at some point to see how much slimmer they are.

**Comment by weinholt** [comment]
The -slim images are ok, but I'd rather not use unofficial base images. Alpine is fine to add under a different tag, like I've done with the chezscheme image. Building on Alpine may not be straightforward in some cases.

**Comment by lassik** [comment]
Avoiding unofficial images is sound policy since we already have tons of other work to do around Scheme. I didn't notice that Chez had an Alpine image already. I tried making an Alpine port of Chibi but as expected, the use of statically linked musl libc is causing a problem. I don't have time to explore more in the near future and the Debian images work fine.

**Comment by lassik** [comment]
Debian `-slim` images cause this note to be displayed: `debconf: delaying package configuration, since apt-utils is not installed`. Does this matter?

**Comment by lassik** [comment]
Also another note from debconf:

```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to
install the Term::ReadLine module) (@INC contains: /etc/perl
/usr/local/lib/x86_64-linux-gnu/perl/5.28.1
/usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28
/usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28
/usr/share/perl/5.28 /usr/local/lib/site_perl
/usr/lib/x86_64-linux-gnu/perl-base)
at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
```

**Comment by lassik** [comment]
Alternatives and lzma:

`update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/lzma.1.gz because associated file /usr/share/man/man1/xz.1.gz (of link group lzma) doesn't exist`

**Comment by weinholt** [comment]
> Debian `-slim` images cause this note to be displayed: `debconf: delaying package configuration, since apt-utils is not installed`. Does this matter?

This does not matter.

> debconf: falling back to frontend: Teletype

Also doesn't matter. These are about configuration prompts when installing packages. There are defaults.

> `update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode update-alternatives: warning: skip creation of /usr/share/man/man1/lzma.1.gz because associated file /usr/share/man/man1/xz.1.gz (of link group lzma) doesn't exist`

We don't use lzma, so this doesn't matter.

**Comment by lassik** [comment]
Actually I think these messages occur with the normal Debian images too. I didn't read the logs carefully before slim.

**Comment by lassik** [comment]
Anyway, can't think of any more concerns for this issue :) The `-slim` images work fine with no effort. Alpine would take much more effort so whoever has the time/need can work on those in the future.
