### ISSUE TITLE
scsh 0.7

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#35]
Please fetch my scsh branch: https://github.com/lassik/scheme-docker/tree/scsh

scsh requires Scheme 48 to run, so this Dockerfile first builds and installs Scheme 48, then builds and installs scsh on top of it. Scheme 48 comes from a release whereas scsh comes from its Git master. A scsh Dockerfile could be written using `FROM` to derive it from the Scheme 48 Dockerfile, but I didn't do that yet.

Scheme 48 installs `scheme-r5rs` and `scheme-srfi-7` commands for running scripts.

All credit to @hga for discovering and documenting [the build steps](https://github.com/scheme-requests-for-implementation/srfi-170/blob/master/scsh-build-notes.org).

**Comment by weinholt** [comment]
Thanks! Pull and added a Docker Hub build. Added SHA256 and git hash verification.
