### ISSUE TITLE
Scheme 48 version 1.9.2

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#36]
Please fetch the new scheme48 branch from my fork: https://github.com/lassik/scheme-docker/tree/scheme48

**Comment by weinholt** [comment]
Thanks! I've pulled your branch and added a build on Docker Hub.

I added SHA256 verification of the download because it's over http. I also changed docker-scheme to scheme-docker to match the other images.

**Comment by lassik** [comment]
Great, thanks. Let me change `banner-scheme` -> `scheme-banner` in the other new images as well before you pull them.

**Comment by lassik** [comment]
Done.
