### ISSUE TITLE
Gambit 4.9.3

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#37]
Please fetch my Gambit branch from https://github.com/lassik/scheme-docker/tree/gambit

Includes the `gsi` interpreter (which is the default command), the `gsc` compiler, and all other commands that come with Gambit.

It's configured with `--enable-single-host` which says that it builds a faster compiler but `docker build` takes a lot RAM.

The default prefix is `/usr/local/Gambit`. I configure with `--prefix /usr/local` which works as expected, except that it puts a bunch of `.scm` files directly into `/usr/local/lib` (not into a subdirectory). It doesn't matter in this Docker container since we don't install anything except Gambit into `/usr/local`.

Ping @feeley

**Comment by lassik** [comment]
@weinholt Wait. I'll change the URL from `http:` to `https:`

**Comment by lassik** [comment]
Done.

**Comment by weinholt** [comment]
Thank you much for this addition! Pulled, pushed and building Docker Hub now.
