### ISSUE TITLE
MIT Scheme 10.1.10

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#38]
Please fetch my `mit-scheme` branch from https://github.com/lassik/scheme-docker/tree/mit-scheme

**Comment by lassik** [comment]
That source tarball is specific to `x86_64`. Can we rely on running that architecture in Docker?

**Comment by weinholt** [comment]
Yes, all the current images are `x86_64` *only* actually. Quite a few of them could be built for other architectures, but I don't know of any way to do this with automatic builds on Docker Hub.

**Comment by lassik** [comment]
MIT Scheme also has an architecture-independent tarball but it requires another copy of MIT Scheme to bootstrap it :p

**Comment by weinholt** [comment]
Catch 22 taken to a metaphysical level.
Pulled, pushed and a build is pending. Thanks!

**Comment by lassik** [comment]
The answer to the age-old question: why are we here?
