### ISSUE TITLE
Add Kawa 3.0

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#39]
What's the slimmest way to install Java on Debian? I tried the `default-jre` package from APT and it didn't even install on `buster-slim`. Then I tried it with normal `buster` and it tried to download like a gigabyte of dependencies before freezing Docker.

**Comment by lassik** [comment]
It tries to download all kinds of X Window System stuff and everything.

**Comment by weinholt** [comment]
```
apt-get --no-install-recommends install default-jre
...
Need to get 71.0 MB of archives.
After this operation, 415 MB of additional disk space will be used.
```

It's a lot, but it's not too much for it to run. Mono is something like this, I think.

**Comment by weinholt** [comment]
There is also default-jre-headless, weighing in at 200 MB in total. I don't know if Kawa will work with that.

**Comment by lassik** [comment]
Headless - that's the good life. I'll give it a try.

**Comment by lassik** [comment]
It worked. Please pull my kawa branch: https://github.com/lassik/scheme-docker/tree/kawa

The image is 337MB. Could be a lot worse. Build with headless JDK, run with headless JRE. Debian slim images did not work - I had to use the normal ones.

**Comment by weinholt** [comment]
The build is up! Thanks a lot!
