### ISSUE TITLE
Add Gerbil 0.15.1

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#42]
Please pull my gerbil branch from https://github.com/lassik/scheme-docker/tree/gerbil

**Comment by lassik** [comment]
Ping @vyzo

**Comment by vyzo** [comment]
We already have a docker container!

**Comment by lassik** [comment]
Yeah, I only noticed the official one when I had already almost finished this one. We have a uniform configuration for these containers so that the default command (`CMD` in the Dockerfile`) starts a REPL, and by manually giving `bash` as the command it goes into a Linux shell. There are also Scheme script wrappers (for the `#!` line) inside most of the containers.

I put a note with a link to the official container in the `Dockerfile` of this one, and Göran should put it in the description field on Docker Hub as well. If you think this unofficial container confuses more than helps, we will remove it.

**Comment by vyzo** [comment]
It's ok, we can keep it around.

**Comment by lassik** [comment]
It would be fun to have a semi-official place for standardized containers of Scheme implementations. Pity that https://hub.docker.com/u/scheme is already taken (and isn't being used for anything).

**Comment by weinholt** [comment]
Thanks people! A build is pending on Docker Hub. I've written a description that points to Gerbil's own image with both hands (or greenish trunk, as the case may be).
