### ISSUE TITLE
Install `tree` program inside containers

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#49]
This is often much more convenient than `ls` because it shows a hierarchical listing. Takes 117 KB of space.

**Comment by weinholt** [comment]
It's not without a cost, but feel free to add it whenever you change something else.

**Comment by lassik** [comment]
This might not be necessary either, after all :) Just realized you can do `docker run -it weinholt/larceny find /usr/local` to list the files installed by an implementation's. I've been meaning to send `tree`'s author a patch for a `--stdin` option since forever. So you could do `docker run -it weinholt/larceny find /usr/local | tree --stdin` and the `tree` outside the container would print you a nice tree based on the `find` inside the container.
