### ISSUE TITLE
Vicare hello world script

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#5]
I can't get a "hello world" working - the script runs but nothing is displayed:

```
$ docker run -it weinholt/vicare
root@a3212dba37e5:/# cat >hello
#! /usr/bin/env scheme-script
(import (rnrs))
(display "Hello world")
(newline)
root@a3212dba37e5:/# chmod +x hello
root@a3212dba37e5:/# ./hello
root@a3212dba37e5:/#
```

**Comment by weinholt** [comment]
Try `(flush-output-port (current-output-port))`. It's a bug/feature in Vicare that it doesn't flush ports on exit.

**Comment by lassik** [comment]
OK, that works. Is Vicare being maintained and do they intend to add flushing eventually?

**Comment by weinholt** [comment]
He has taken a break from Vicare. It's in here somewhere: https://marcomaggi.github.io/weblog/Posts.html#Posts
I don't know if he intends to add flushing. It could be one of those cases of strict conformance to the spec. Is there anything in RnRS that requires a flush? :)

**Comment by lassik** [comment]
I don't know whether the spec mandates it but we run the script using a dedicated `--r6rs-script` flag. For that use case the lack of auto-flushing is surprising.

But I respect anyone's need to rest and do other things :) He is clearly a very talented and dedicated guy.

**Comment by lassik** [comment]
Anyway, closing since this is not a problem we should address in the Docker scripts :)
