### ISSUE TITLE
Add Oaklisp

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#60]
Made an oaklisp branch based on the Oaklisp 1.3.7 tarball from github (the "upstream" one, not the "debian" one - not sure what the difference is)

**Comment by lassik** [comment]
This is 32-bit only. Author says he knows how to port it to 64bit but just hasn't found the time. https://github.com/barak/oaklisp/issues/5

**Comment by weinholt** [comment]
Barak! Didn't know he had his own Scheme. Upstream is more likely to be right, debian is probably for Debian (he's also a DD).
Build added.

**Comment by lassik** [comment]
Doesn't everyone :D

Since you two are Debian devs, could you organize some effort to get these Schemes into APT? We've already paid most of the dues making these Dockerfiles.
