### ISSUE TITLE
Add SCM

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#62]
Made a scm branch using the latest release of the SCM and SLIB zipfiles from the SCM homepage http://people.csail.mit.edu/jaffer/SCM

**Comment by weinholt** [comment]
The anscestor of Guile, I think. Build added.

**Comment by lassik** [comment]
Pushed some fixes. Are Docker Hub builds triggered automatically by GitHub commits?

**Comment by weinholt** [comment]
Yep, once I've created the build, it's all automatic.
