### ISSUE TITLE
Add Elk

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#63]
Made an elk branch with the latest tarball of elk from its homepage http://sam.zoy.org/elk/. Build was easy, making scheme-banner was hard. It defines a `scheme-implementation-version` procedure but it's in `slib.scm` and `(require 'slib)` gives some error I don't understand.

**Comment by weinholt** [comment]
Another DD, famous for WTFPL and libcaca.
Build added.

**Comment by lassik** [comment]
Great. You guys need to organize an APT submitting spree!

**Comment by lassik** [comment]
I had no idea WTFPL came from a Schemer :) We are a multi-talented bunch.
