### ISSUE TITLE
Add STklos

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#64]
Build requires a terminal, cannot run headless. https://github.com/egallesio/STklos/issues/2

**Comment by lassik** [comment]
This is still being actively worked on!

**Comment by lassik** [comment]
This Scheme is still being actively worked on!

**Comment by lassik** [comment]
Got STklos working thanks to help from @egallesio! In the current release, `make` does not work when the `TERM` environment variable isn't defined. The build doesn't actually require a tty or pty, just the envar.

Please delete the `stklos-attempt` and `stklos-wip` branches which contain unfinished versions of the Dockerfile.

**Comment by lassik** [comment]
The working Dockerfile is in the `stklos` branch.

**Comment by weinholt** [comment]
Great work. Building now!
