### ISSUE TITLE
New Cyclone Scheme 0.11.4 release

### ISSUE THREAD

**Issue by justinethier** [weinholt/scheme-docker#76]
@lassik per your request, can you please update the Cyclone container to support the new 0.11.4 release?

**Comment by lassik** [comment]
@justinethier Thank you for notifying us! Added, build and tested. Everything works fine.

`docker run -it weinholt/cyclone` -> goes to icyc

`docker run -it weinholt/cyclone bash` -> goes into a shell where you can compile programs
