### ISSUE TITLE
Cyclone directory rename

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#78]
Following Kawa and Chicken, also renamed the Cyclone directory to `0.x`, dropping the distinction between different minor versions.

**Comment by weinholt** [comment]
It builds again.

Might I gently nudge us towards putting most of these containers under https://hub.docker.com/u/schemers so we both can fix the builds? :)

**Comment by lassik** [comment]
Thanks.

Yes, you might :) That's a good idea. I've been procrastinating on the container stuff far too long anyway for no particular reason. Let's go with "schemers" until we get "scheme" as you suggest. I give up on my persistence.
